create table branch (
  branch_id int not null generated by default as identity,
  description varchar(50),
  branch_code varchar(20),
  primary key (branch_code)
);

create table vaccine (
  vaccine_id int not null generated by default as identity,
  description varchar(50),
  vaccine_code varchar(20),
  primary key (vaccine_code)
);

CREATE TABLE branch_vaccine(
    branch_vaccine_id int not null generated by default as identity,
    branch_code varchar(20) not null,
    vaccine_code varchar(20) not null,
    primary key (branch_vaccine_id),
    CONSTRAINT FK_Branch FOREIGN KEY (branch_code) REFERENCES branch(branch_code),
    CONSTRAINT FK_Vaccine FOREIGN KEY (vaccine_code) REFERENCES vaccine(vaccine_code)
);

create table payment_method (
  payment_method_id int not null generated by default as identity,
  description varchar(50),
  primary key (payment_method_id)
);


create table time_slot (
  time_slot_id int not null generated by default as identity,
  from_time varchar(20),
  to_time varchar(20),
  primary key (time_slot_id)
);

CREATE TABLE customer(
    customer_id  int not null generated by default as identity,
    customer_name varchar(50),
    customer_national_number varchar(20),
    email varchar(50),
    primary key (customer_id)
);

CREATE TABLE vaccination_schedule(
    vaccination_schedule_id int not null generated by default as identity,
    vaccination_schedule_code varchar(50) NOT NULL,
    schedule_date DATE NOT NULL,
    time_slot_id int NOT NULL,
    branch_code varchar(20) NOT NULL,
    vaccine_code varchar(20) NOT NULL,
    customer_id int NOT NULL,
    payment_method_id int NOT NULL,
    confirmed BOOLEAN not null default FALSE,
    applied BOOLEAN not null default FALSE,
    primary key (vaccination_schedule_id),
    CONSTRAINT FK_Schedule_TimeSlot FOREIGN KEY (time_slot_id) REFERENCES time_slot(time_slot_id),
    CONSTRAINT FK_Schedule_BranchCode FOREIGN KEY (branch_code) REFERENCES branch(branch_code),
    CONSTRAINT FK_Schedule_VaccineCode FOREIGN KEY (vaccine_code) REFERENCES vaccine(vaccine_code),
    CONSTRAINT FK_Schedule_CustomerId FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT FK_Schedule_PaymentMethod FOREIGN KEY (payment_method_id) REFERENCES payment_method(payment_method_id)
);