INSERT INTO branch(description, branch_code) VALUES('Burjuman', 'BURJ');
INSERT INTO branch(description, branch_code) VALUES('Jumeira', 'JUME');
INSERT INTO branch(description, branch_code) VALUES('Sharjah', 'SHAR');

INSERT INTO vaccine(description, vaccine_code) VALUES('Sinopharm Vaccine', 'SINO');
INSERT INTO vaccine(description, vaccine_code) VALUES('Pfizer Vaccine', 'PFZR');
INSERT INTO vaccine(description, vaccine_code) VALUES('Moderna Vaccine', 'MDRN');

INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('BURJ', 'SINO');
INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('BURJ', 'PFZR');
INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('BURJ', 'MDRN');
INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('JUME', 'SINO');
INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('JUME', 'PFZR');
INSERT INTO branch_vaccine(branch_code, vaccine_code) VALUES('SHAR', 'PFZR');

INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '8:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '8:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '8:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '9:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '9:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '9:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '9:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '10:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '10:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '10:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '10:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '11:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '11:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '11:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '11:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '12:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '12:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '12:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '13:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '13:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '13:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '13:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '14:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '14:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '14:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '14:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '15:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '15:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '15:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '15:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '16:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '16:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '16:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '16:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '17:00');
INSERT INTO time_slot(from_time, to_time) VALUES('8:00', '17:15');
INSERT INTO time_slot(from_time, to_time) VALUES('8:15', '17:30');
INSERT INTO time_slot(from_time, to_time) VALUES('8:30', '17:45');
INSERT INTO time_slot(from_time, to_time) VALUES('8:45', '18:00');

INSERT INTO payment_method(description) VALUES('Cash');
INSERT INTO payment_method(description) VALUES('Credit');
INSERT INTO payment_method(description) VALUES('Fawry');
